name: GlassStudio

options:
  deploymentTarget:
    iOS: "15.0"

targets:
  GlassStudio:
    type: application
    platform: iOS
    sources:
      - GlassStudio
    resources:
      - path: Website/index.html
      - path: Website/style.css
      - path: Website/script.js
      - path: Website/logo.png
      - path: Website/favicon.ico
      - path: Website/not_found.html
      - path: Website/robots.txt
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: anar.neo.glassstudio
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.0"