name: GlassStudio

options:
  deploymentTarget:
    iOS: "15.0"

targets:
  GlassStudio:
    type: application
    platform: iOS
    sources:
      - GlassStudio
    resources:
  - Website/index.html
  - Website/style.css
  - Website/script.js
  - Website/logo.png
  - Website/favicon.ico
  - Website/not_found.html
    info:
      path: Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: anar.neo.glassstudio
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.0"